name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:  # placeholder for future db needs
        image: postgres:16-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: dummy

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Backend deps + tests
        run: |
          cd backend
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
          pytest -q

      - name: Frontend build
        run: |
          cd frontend
          npm ci
          npm run build